#Configuration file

#Dir and path
Dir:
  cl_dir: './cl_data/'
  input_dir: './input/'
  results_dir: './results/'
  img_dir: './results/img'
  output_dir: './results/output'

Grid:
  temp_min: -15 #˚C
  temp_max: 41.0 #˚C
  temp_step: 1.0 #˚C
  pres_min: 80000 #Pa
  pres_max: 101900 #Pa
  pres_step: 250 #Pa
  hum_min: 0.0 #%
  hum_max: 100 #%
  hum_step: 10.0 #%
  wind_min: 0.0 #m/s
  wind_max: 25.0 #m/s
  wind_step: 1.0 #m/s
  fixed_params: [ "Humidity", "Pressure" ] #allowed keywords : "Temperature" ,"Headwind", "Humidity", "Pressure"

#Aircraft specifications
Aircraft:
  aircr_name: 'A320'
  aircr_engine: 'V2500-A1'

#Airport specifications (try to autom via airportsdata)
Airport:
  airport_code: 'LIPE' #London =  EGLL , Bruxells =  EBBR, Pantelleria = LICG

#Climate data selection
Climate:
  model: 'ACCESS-ESM1-5' #UKESM1-0-LL or ACCESS-ESM1-5
  months: [ 6, 7, 8 ] # month(s) number

#Mass limitation:
Mass:
  passenger_mass: 86.0 #kg
