# Configuration file for aircraft takeoff performance simulation
#
# Sections:
# - Dir: Directory paths for data, inputs, results, images, and outputs.
# - Grid: Parameter ranges and steps for environmental conditions (temperature, pressure, humidity, wind).
# - Aircraft: Aircraft and engine identifiers.
# - Airport: Airport code for location-specific data.
# - Climate: Climate model and months selection for environmental data.
# - Mass: Passenger mass specification used for weight calculations.
#
# Example values are provided for a typical setup with an A320 aircraft,
# ACCESS-ESM1-5 climate model, and LIPE airport.

#Author: Lorenzo Cane - DBL E&E Area Consultant
#Last modified: 20/06/2025

#Dir and path
Dir:
  cl_dir: './cl_data/'
  input_dir: './input/'
  results_dir: './results/'
  img_dir: './results/img'
  output_dir: './results/output'

#Grid
Grid:
  temp_min: -15 #˚C
  temp_max: 40.0 #˚C
  temp_step: 1.0 #˚C
  pres_min: 80000 #Pa
  pres_max: 102000 #Pa
  pres_step: 250 #Pa
  hum_min: 0.0 #%
  hum_max: 100 #%
  hum_step: 10.0 #%
  wind_min: 0.0 #m/s
  wind_max: 25.0 #m/s
  wind_step: 1.0 #m/s
  fixed_params: [ "Humidity", "Pressure" ] #allowed keywords : "Temperature" ,"Headwind", "Humidity", "Pressure"

#Aircraft specifications
Aircraft:
  aircr_name: 'A320'
  aircr_engine: 'V2500-A1'

#Airport specifications (try to autom via airportsdata)
Airport:
  airport_code: 'LIPE' #London =  EGLL , Bruxells =  EBBR, Pantelleria = LICG

#Climate data selection
Climate:
  model: 'ACCESS-ESM1-5' #UKESM1-0-LL or ACCESS-ESM1-5
  months: [ 6, 7, 8 ] # month(s) number

#Mass limitation:
Mass:
  passenger_mass: 86.0 #kg
